---
title: "lme_mods"
author: "Jacob Salminen"
date: "2024-04-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages & Setup
```{r}
# install.packages(c("tidyverse","purrr","R.matlab","readxl","dplyr"))
library(readxl);
library(purrr)
library(tidyverse);
library(tibble)
library(knitr);
library(gtsummary)
library(kableExtra)
library(lme4)
```

## GTSUMMARY THEME
``` {r}
# my_theme <-
#   list(
#     "tbl_summary-str:default_con_type" = "continuous2",
#     "tbl_summary-str:continuous_stat" = c(
#       "{median} ({p25} - {p75})",
#       "{mean} ({sd})",
#       "{min} - {max}"
#     ),
#     "tbl_summary-str:categorical_stat" = "{n} / {N} ({p}%)",
#     "style_number-arg:big.mark" = "",
#     "tbl_summary-fn:percent_fun" = function(x) style_percent(x, digits = 3)
#   )
# my_theme <-
#   list()
# gtsummary::set_gtsummary_theme(my_theme)
gtsummary::set_gtsummary_theme(theme_gtsummary_journal("jama"))
# reset_gtsummary_theme()
```

## load table 
```{r} 
# excel_dir <-"M:/jsalminen/GitHub/par_EEGProcessing/src/_data/MIM_dataset/_studies/04162024_MIM_YAOAN89_antsnormalize_iccREMG0p4_powpow0p3_skull0p01/cluster/icrej_5/12/spec_data/group_spec/psd_calcs/fooof_kinematics_table.xlsx";
excel_dir <-"M:/jsalminen/GitHub/par_EEGProcessing/src/_data/MIM_dataset/_studies/04232024_MIM_YAOAN89_antsnormalize_iccREMG0p4_powpow0p3_skull0p01_15mmrej/cluster/icrej_5/12/spec_data/group_spec/psd_calcs/fooof_kinematics_table.xlsx";
eegt <- read_excel(excel_dir,sheet="Sheet1") 
```

## get unique entries 
```{r} 
clusters = unique(eegt$cluster_id);
subjects = unique(eegt$subj_char);
groups = unique(eegt$group_char);
kin_measures = c('mean_APexc_COV','mean_APexc_mean','mean_MLexc_COV','mean_MLexc_mean','mean_StepDur','mean_UDexc_COV','mean_UDexc_mean','mean_StanceDur','mean_GaitCycleDur','mean_PeakUpDownVel_mean');
eeg_measures = c('theta_avg_power','alpha_avg_power','beta_avg_power','aperiodic_exp','aperiodic_offset');
```

## get speeds only 
```{r} 
eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('0.25','0.5','0.75','1.0')))
flat_speeds = unique(eegt$cond_char)
eegt$cond_char <- as.numeric(eegt$cond_char)
eegt$speed_cond_num <- as.numeric(eegt$cond_char)
eegt <- mutate(eegt,across(c('subj_char'), factor))
```

## get terrains only (if applicable)
``` {r}
# eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('flat','low','med','high')))
# eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('high')))
# eegt$terr_ord_speed <- cut(eegt$speed_ms, 4, ordered = TRUE)
```

## convert speeds to ordered & groups to factors 
```{r conversions}
eegt <- mutate(eegt,across(c('group_char'), factor))
eegt$speed_ord <- cut(eegt$cond_char, 4, ordered = TRUE)
eegt <- mutate(eegt,across(c('cond_char'), factor))
head(eegt)
eegt$group_speed_code = paste(eegt$group_char,eegt$cond_char,sep="_")
```

# LME EEG ~ 1+speed+group+speed:group
```{r EEG ~ 1+speed+group+speed:group, echo=FALSE, message=FALSE, results="asis"}
library(gtsummary)
cat('\n\n<!-- -->\n\n')
inter_pvalue = vector(mode="logical");
for (ci in 1:length(clusters)) {
  tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% clusters[ci]));
  tbl <- tibble(outcome=eeg_measures[1:3]) %>%
    rowwise() %>%
    mutate(
      tbl = 
        lmer(str_glue("{outcome} ~ 1 + speed_cond_num + group_char + speed_cond_num:group_char + (1|subj_char)"), data=tmpt) %>%
        tbl_regression(tidy_fun = broom.mixed::tidy,
                       pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                       intercept=TRUE) %>%
        add_global_p() %>%
        add_q() %>%
        list()
      ) %>%
    pull(tbl) %>%
    tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**"))
  # for (j in 1:length(tbl$tbl)) {
  #   append(inter_pvalue[j],tbl$tbl[j][[1]]$table_body$p.value[7]<0.05)
  # }
  # tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**","**Aperiodic Exp.**","**Aperiodic Offset**"))
  
  # t_out <- as_gt(tbl) %>%
  #   gt::tab_header(title=c("Cluster: ",clusters[ci])) %>%
  #   gt::tab_options(table.layout = "fixed") %>%
  #   gt::as_latex()
  
  t_out <- as_kable_extra(tbl, format = "latex") %>%
    add_header_above(c("Cluster: ",clusters[ci])) %>%
    kable_styling(latex_options="scale_down")
  # tbl
  
  # print(t_out)
  cat(knitr::knit_print(t_out));
  cat('\n\n<!-- -->\n\n')
}
```
<!-- \clearpage -->
# LME EEG ~ 1+speed+group
```{r EEG ~ 1+speed+group, echo=FALSE, message=FALSE, results="asis"}
library(gtsummary)
cat('\n\n<!-- -->\n\n')
inter_pvalue = vector(mode="logical");
for (ci in 1:length(clusters)) {
  tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% clusters[ci]));
  tbl <- tibble(outcome=eeg_measures[1:3]) %>%
    rowwise() %>%
    mutate(
      tbl = 
        lmer(str_glue("{outcome} ~ 1 + speed_cond_num + group_char + (1|subj_char)"), data=tmpt) %>%
        tbl_regression(tidy_fun = broom.mixed::tidy,
                       pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                       intercept=TRUE) %>%
        add_global_p() %>%
        add_q() %>%
        list()
      ) %>%
    pull(tbl) %>%
    tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**"))
  # for (j in 1:length(tbl$tbl)) {
  #   append(inter_pvalue[j],tbl$tbl[j][[1]]$table_body$p.value[7]<0.05)
  # }
  # tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**","**Aperiodic Exp.**","**Aperiodic Offset**"))
  # t_out <- as_gt(tbl) %>%
  #   gt::tab_header(title=c("Cluster: ",clusters[ci])) %>%
  #   gt::tab_options(table.layout = "fixed") %>%
  #   gt::as_latex()
  
  t_out <- as_kable_extra(tbl, format = "latex") %>%
    add_header_above(c("Cluster: ",clusters[ci])) %>%
    kable_styling(latex_options="scale_down")
  # tbl
  
  # print(t_out)
  cat(knitr::knit_print(t_out));
  cat('\n\n<!-- -->\n\n')
}
```
<!-- \clearpage -->

# LME KIN ~ 1+speed+group+speed:group
```{r KIN ~ 1+speed+group+speed:group, echo=FALSE, message=FALSE, results="asis"}
library(gtsummary)
cat('\n\n<!-- -->\n\n')
for (ci in 1:length(clusters)) {
  tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% clusters[ci]));
  tbl <- tibble(outcome=kin_measures) %>%
    rowwise() %>%
    mutate(
      tbl = 
        lmer(str_glue("{outcome} ~ 1 + speed_cond_num + group_char + speed_cond_num:group_char + (1|subj_char)"), data=tmpt) %>%
        tbl_regression(tidy_fun = broom.mixed::tidy,
                       pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                       intercept=TRUE) %>%
        add_global_p() %>%
        add_q() %>%
        list()
      ) %>%
    pull(tbl) %>%
    tbl_merge(tab_spanner=c("APexc COV","APexc","MLexc COV","MLexc","Step Dur","UDexc COV","UDexc","Stance Dur","GaitCycle Dur","Peak UpDown Vel"))
    # tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**","**Aperiodic Exp.**","**Aperiodic Offset**"))
  # t_out <- as_gt(tbl) %>%
  #   gt::tab_header(title=c("Cluster: ",clusters[ci])) %>%
  #   gt::tab_options(table.layout = "fixed") %>%
  #   gt::as_latex()
  
  t_out <- as_kable_extra(tbl, format = "latex") %>%
    add_header_above(c("Cluster: ",clusters[ci])) %>%
    kable_styling(latex_options="scale_down")
  # tbl
  
  # print(t_out)
  cat(knitr::knit_print(t_out));
  cat('\n\n<!-- -->\n\n')
}
```
<!-- \clearpage -->
# LME KIN ~ 1+speed+group
```{r KIN ~ 1+speed+group, echo=FALSE, message=FALSE, results="asis"}
library(gtsummary)
cat('\n\n<!-- -->\n\n')
for (ci in 1:length(clusters)) {
  tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% clusters[ci]));
  tbl <- tibble(outcome=kin_measures) %>%
    rowwise() %>%
    mutate(
      tbl = 
        lmer(str_glue("{outcome} ~ 1 + speed_cond_num + group_char + (1|subj_char)"), data=tmpt) %>%
        tbl_regression(tidy_fun = broom.mixed::tidy,
                       pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                       intercept=TRUE) %>%
        add_global_p() %>%
        add_q() %>%
        list()
      ) %>%
    pull(tbl) %>%
    tbl_merge(tab_spanner=c("APexc COV","APexc","MLexc COV","MLexc","Step Dur","UDexc COV","UDexc","Stance Dur","GaitCycle Dur","Peak UpDown Vel"))
    # tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**","**Aperiodic Exp.**","**Aperiodic Offset**"))
  # t_out <- as_gt(tbl) %>%
  #   gt::tab_header(title=c("Cluster: ",clusters[ci])) %>%
  #   gt::tab_options(table.layout = "fixed") %>%
  #   gt::as_latex()
  
  t_out <- as_kable_extra(tbl, format = "latex") %>%
    add_header_above(c("Cluster: ",clusters[ci])) %>%
    kable_styling(latex_options="scale_down")
  # tbl
  
  # print(t_out)
  cat(knitr::knit_print(t_out));
  cat('\n\n<!-- -->\n\n')
}
```
<!-- \clearpage -->
# LME EEG ~ 1+kin+group+kin:group
```{r EEG ~ 1+kin+group+kin:group, echo=FALSE, message=FALSE, results="asis"}
library(gtsummary)
cat('\n\n<!-- -->\n\n')
for (ci in 1:length(clusters)) {
  tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% clusters[ci]));
  for (mi in 1:length(kin_measures)) {
    tbl <- tibble(outcome=eeg_measures[1:3]) %>%
      rowwise() %>%
      mutate(
        tbl = 
          lmer(str_glue(paste("{outcome} ~ 1 +",kin_measures[mi],"+ group_char + ",kin_measures[mi],":group_char + (1|subj_char)")), data=tmpt) %>%
          tbl_regression(tidy_fun = broom.mixed::tidy,
                         pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                         intercept=TRUE) %>%
          add_global_p() %>%
          add_q() %>%
          list()
        ) %>%
      pull(tbl) %>% 
      tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**"))
      # tbl_merge(tab_spanner=c("**APexc COV**","**APexc**","**MLexc COV**","**MLexc**","**Step Dur**","**UDexc COV**","**UDexc**","**Stance Dur**","**GaitCycle Dur**","**Peak UpDown Vel**"))
      # tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**"))
      # tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**","**Aperiodic Exp.**","**Aperiodic Offset**"))
    
    # t_out <- as_gt(tbl) %>%
    #   gt::tab_header(title=c("Changes in ",eeg_measures[mi],"for Cluster: ",clusters[ci])) %>%
    #   gt::tab_options(table.layout = "fixed") %>%
    #   gt::as_latex()
    
    t_out <- as_kable_extra(tbl, format = "latex") %>%
      add_header_above(c("Changes in ",kin_measures[mi],"for Cluster: ",clusters[ci])) %>%
      kable_styling(latex_options="scale_down")
    # tbl
    
    # print(t_out)
    cat(knitr::knit_print(t_out));
    cat('\n\n<!-- -->\n\n')
  }
}
```
<!-- \clearpage -->
# LME EEG ~ 1+kin+group
```{r EEG ~ 1+kin+group, echo=FALSE, message=FALSE, results="asis"}
library(gtsummary)
cat('\n\n<!-- -->\n\n')
for (ci in 1:length(clusters)) {
  tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% clusters[ci]));
  for (mi in 1:length(kin_measures)) {
    tbl <- tibble(outcome=eeg_measures[1:3]) %>%
      rowwise() %>%
      mutate(
        tbl = 
          lmer(str_glue(paste("{outcome} ~ 1 +",kin_measures[mi],"+ group_char + (1|subj_char)")), data=tmpt) %>%
          tbl_regression(tidy_fun = broom.mixed::tidy,
                         pvalue_fun = purrr::partial(style_pvalue, digits = 2),
                         intercept=TRUE) %>%
          add_global_p() %>%
          add_q() %>%
          list()
        ) %>%
      pull(tbl) %>% 
      tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**"))
      # tbl_merge(tab_spanner=c("**APexc COV**","**APexc**","**MLexc COV**","**MLexc**","**Step Dur**","**UDexc COV**","**UDexc**","**Stance Dur**","**GaitCycle Dur**","**Peak UpDown Vel**"))
      # tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**"))
      # tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**","**Aperiodic Exp.**","**Aperiodic Offset**"))
    
    # t_out <- as_gt(tbl) %>%
    #   gt::tab_header(title=c("Changes in ",eeg_measures[mi],"for Cluster: ",clusters[ci])) %>%
    #   gt::tab_options(table.layout = "fixed") %>%
    #   gt::as_latex()
    
    t_out <- as_kable_extra(tbl, format = "latex") %>%
      add_header_above(c("Changes in ",kin_measures[mi],"for Cluster: ",clusters[ci])) %>%
      kable_styling(latex_options="scale_down")
    # tbl
    
    # print(t_out)
    cat(knitr::knit_print(t_out));
    cat('\n\n<!-- -->\n\n')
  }
}
```
<!-- \clearpage -->