---
title: "md_summary_contrasts"
author: "Jacob Salminen"
date: "2024-04-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r}
# install.packages(c("tidyverse","purrr","R.matlab","readxl","dplyr"))
library(readxl);
library(purrr)
library(tidyverse);
library(tibble)
library(knitr);
library(gtsummary)
```

## GTSUMMARY THEME
``` {r}
my_theme <-
  list(
    "tbl_summary-str:default_con_type" = "continuous2",
    "tbl_summary-str:continuous_stat" = c(
      "{median} ({p25} - {p75})",
      "{mean} ({sd})",
      "{min} - {max}"
    ),
    "tbl_summary-str:categorical_stat" = "{n} / {N} ({p}%)",
    "style_number-arg:big.mark" = "",
    "tbl_summary-fn:percent_fun" = function(x) style_percent(x, digits = 3)
  )
# my_theme <-
#   list()
# gtsummary::set_gtsummary_theme(my_theme)
gtsummary::set_gtsummary_theme(theme_gtsummary_journal("jama"))
reset_gtsummary_theme()
```

## load table 
```{r} 
excel_dir <-"M:/jsalminen/GitHub/par_EEGProcessing/src/_data/MIM_dataset/_studies/04162024_MIM_YAOAN89_antsnormalize_iccREMG0p4_powpow0p3_skull0p01/cluster/icrej_5/12/spec_data/group_spec/psd_calcs/fooof_kinematics_table.xlsx";
eegt <- read_excel(excel_dir,sheet="Sheet1") 
```

### get unique entries 
```{r} 
clusters = unique(eegt$cluster_id);
subjects = unique(eegt$subj_char);
groups = unique(eegt$group_char);
eeg_measures = c('theta_avg_power','alpha_avg_power','beta_avg_power','aperiodic_exp','aperiodic_offset');
```

### get speeds only 
```{r} 
eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('0.25','0.5','0.75','1.0')))
flat_speeds = unique(eegt$cond_char)
eegt$cond_char <- as.numeric(eegt$cond_char)
```

### get terrains only (if applicable)
``` {r}
# eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('flat','low','med','high')))
# eegt <- filter_at(eegt,vars('cond_char'), any_vars(. %in% c('high')))
# eegt$terr_ord_speed <- cut(eegt$speed_ms, 4, ordered = TRUE)
```

### convert speeds to ordered & groups to factors 
```{r conversions}
eegt <- mutate(eegt,across(c('group_char'), factor))
eegt$speed_ord <- cut(eegt$cond_char, 4, ordered = TRUE)
eegt <- mutate(eegt,across(c('cond_char'), factor))
head(eegt)
```
### LOOP through clusters & get constrast summaries
```{r contrasts tables}
for (ci in 1:length(clusters)) {
  tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% clusters[ci]));
  contrasts(tmpt$speed_ord) = contr.poly(4)
  print(tbl <- tibble(outcome=eeg_measures) %>%
    rowwise() %>%
    mutate(
      tbl = 
        lm(str_glue("{outcome} ~ 1 + speed_ord"), data=tmpt) %>%
        tbl_regression(intercept = TRUE) %>%
        add_significance_stars(
          hide_se = TRUE,
          hide_ci = FALSE
        ) %>%
        list()
    ) %>%
    pull(tbl) %>%
    tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**","**Aperiodic Exp.**","**Aperiodic Offset**")) %>%
    as_gt() %>%
    gt::tab_header(title=c("Cluster: ",clusters[ci])))
}
```
### LOOP through clusters & get constrast summaries 
```{r contrasts}
# contrasts(eegt$speed_ord) = contr.poly(4)
# invisible(
# for (ci in 1:length(clusters)) {
#   for (mi in 1:length(eeg_measures)) {
#     cat("## Cluster: ",clusters[ci],"EEG Measure",eeg_measures[mi],"\n")
#     tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% clusters[ci]));
#     # get means 
#     tapply(tmpt[[eeg_measures[mi]]],tmpt$speed_ord,mean)
#     # create contrast levels
#     # contr.poly(4) # check their values (different for different amount of levels)
#     contrasts(tmpt$speed_ord) = contr.poly(4)
#     mod = reformulate("1+speed_ord",response=eeg_measures[mi])
#     # fit <- lm(mod,tmpt);
#     print(tmpt %>%
#       lm(mod,data = .) %>%
#       gtsummary::tbl_regression(intercept = TRUE) %>%
#         add_significance_stars(
#           hide_se=TRUE,
#           hide_ci=FALSE
#         ))
#     # %>%
#     #   as_gt() %>%
#     #   gt::tab_header(title=C("## Cluster: ",clusters[ci],"EEG Measure",eeg_measures[mi],"\n"))
#       
#   }
# }
# )
```
```{r}
library(rstatix)
library(tidyverse)
library(ggpubr)
# for (ci in 1:length(clusters)) {
#   tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% clusters[ci]));
#   print(
#     tbl <- tibble(outcome=eeg_measures) %>%
#     rowwise() %>%
#     mutate(
#       tbl = 
#         pairwise_t_test("{outcome}~group_speed_code",data=tmpt)
#         ) %>%
#         list()
#     ) %>%
#     pull(tbl) %>%
#     tbl_merge(tab_spanner=c("**EEG Theta**","**EEG Alpha**","**EEG Beta**","**Aperiodic Exp.**","**Aperiodic Offset**")) %>%
#     as_gt() %>%
#     gt::tab_header(title=c("Cluster: ",clusters[ci])))
# }
# ci = 1;
# mi = 1;
# gi = 1;
# gj = 2;
# si = 1;
# sj = 2;
eegt$group_speed_code = paste(eegt$group_char,eegt$cond_char,sep="_")
for (ci in 1:length(clusters)) {
  tmpt <- filter_at(table_out,vars('cluster_id'), any_vars(. %in% clusters[ci]));
  tbl <- eegt %>% 
    filter_at(vars('cluster_id'), any_vars(. %in% clusters[ci])) %>%
    select(group_speed_code,alpha_avg_power,theta_avg_power,beta_avg_power,aperiodic_exp,aperiodic_offset) %>%
    pairwise_t_test(alpha_avg_power~group_speed_code)
}
# output <- tmpt %>%
#   select(group_speed_code,alpha_avg_power,theta_avg_power,beta_avg_power,aperiodic_exp,aperiodic_offset) %>%
#   pivot_longer(cols=all_of(eeg_measures),names_to=c("variables"),values_to="value") %>%
#   group_by(variables) %>%
#   summarize_at(
#             vars(-group_cols(), -group_speed_code),
#             list(pairwise_t_test = ~list(pairwise_t_test(. ~ group_speed_code))))
#
# tbl <- eegt %>% 
#   filter_at(vars('cluster_id'), any_vars(. %in% clusters[ci]))
#   select(group_speed_code,alpha_avg_power,theta_avg_power,beta_avg_power,aperiodic_exp,aperiodic_offset) %>%
#   pairwise_t_test(value~group_speed_code)
# create a long table
# long_tbl <- tmpt %>%
#   select(group_speed_code,alpha_avg_power,theta_avg_power,beta_avg_power,aperiodic_exp,aperiodic_offset) %>%
#   pivot_longer(cols=all_of(eeg_measures),names_to=c("variables"),values_to="value") %>%
#   pivot_longer(cols=c(group_char,cond_char),names_to=c("dummy"),values_to=c("groupings")) %>%
#   group_by(variables) %>%
#   pairwise_t_test(value~groupings)
# # Pairwise comparisons
# tmpt %>%
#   group_by(cond_char,group_char) 
#   get_summary_stats(alpha_avg_power,type="mean_sd")
# pwc <- tmpt %>%
#   pairwise_t_test(alpha_avg_power~group_char, p.adjust.method = "bonferroni")
# pwc
# 
# #
# tmpt %>%
#   group_by(cond_char) %>%
#   group_map(~ t.test(alpha_avg_power ~ group_char, .x, paired = TRUE))
```
### LOOP through clusters & get ttests
```{r ttests, echo=FALSE, message=FALSE}
# s1 = c(0.25,0.5,0.75,1.0,0.25,0.25,0.25,0.5,0.5,0.75)
# s2 = c(0.25,0.5,0.75,1.0,0.5,0.75,1.0,0.75,1.0,1.0)
# g1 = c("H1000's","H2000's","H3000's","H1000's","H1000's","H2000's")
# g2 = c("H1000's","H2000's","H3000's","H2000's","H3000's","H3000's")
# invisible(
# for (ci in 1:length(clusters)) {
#   tmpt <- filter_at(eegt,vars('cluster_id'), any_vars(. %in% clusters[ci]));
#   for (mi in 1:length(eeg_measures)) {
#     sidone <- vector(mode="numeric")
#     for (si in 1:length(flat_speeds)) {
#       # tsi <- filter_at(tmpt,vars('cond_char'), any_vars(. %in% flat_speeds[si]));
#       for (sj in 1:length(flat_speeds)) {
#         # tsj <- filter_at(tmpt,vars('cond_char'), any_vars(. %in% flat_speeds[sj]));
#         gidone <- vector(mode="numeric")
#         if (!any(match(sidone,sj,nomatch=FALSE))) {
#           for (gi in 1:length(groups)) {
#             # tgi <- filter_at(tsi,vars('group_char'), any_vars(. %in% groups[gi]));
#             for (gj in 1:length(groups)) {
#               # tgj <- filter_at(tsj,vars('group_char'), any_vars(. %in% groups[gj]));
#               if (!any(match(gidone,gj,nomatch=FALSE))) {
#                 if ((gi==gj && si!=sj) || (gi!=gj && si==sj) || (gi!=gj && si!=sj)) {
#                   cat("## EEG Measure: ",eeg_measures[mi]," Speed1: ",flat_speeds[si]," Speed2: ",flat_speeds[sj]," Group1: ",groups[gi]," Group2: ",groups[gj],"\n");
#                   print(
#                     tbl <- 
#                       tmpt %>%
#                       filter_at(vars(cond_char),any_vars(. %in% c(flat_speeds[si],flat_speeds[sj]))) %>%
#                       filter_at(vars(group_char),any_vars(. %in% c(groups[gi],groups[gj]))) %>%
#                       select(group_char,alpha_avg_power,theta_avg_power,beta_avg_power,aperiodic_exp,aperiodic_offset,cond_char) %>%
#                       tbl_strata(strata=group_char,
#                                  .tbl_fun=
#                                    ~ .x %>%
#                                    tbl_summary(by=cond_char,missing="no") %>%
#                                    add_n() %>%
#                                    add_p(test=all_categorical()~"t.test"),
#                                  .header="**{strata}**,N={n}")
#                     )
#                 }
#               }
#             }
#           gidone <- append(gidone, gi);
#           }
#         }
#       }
#       sidone <- append(sidone, si);
#     }
#   }
# }
# )
```

### LOOP through clusters & get ttests
```{r ground truth ttests, echo=FALSE, message=FALSE}
# s1 = c(0.25,0.5,0.75,1.0,0.25,0.25,0.25,0.5,0.5,0.75)
# s2 = c(0.25,0.5,0.75,1.0,0.5,0.75,1.0,0.75,1.0,1.0)
# g1 = c("H1000's","H2000's","H3000's","H1000's","H1000's","H2000's")
# g2 = c("H1000's","H2000's","H3000's","H2000's","H3000's","H3000's")
invisible(
for (ci in 1:length(clusters)) {
  tmpt <- filter_at(table_out,vars('cluster_id'), any_vars(. %in% clusters[ci]));
  for (mi in 1:length(eeg_measures)) {
    sidone <- vector(mode="numeric")
    for (si in 1:length(flat_speeds)) {
      tsi <- filter_at(tmpt,vars('cond_char'), any_vars(. %in% flat_speeds[si]));
      for (sj in 1:length(flat_speeds)) {
        tsj <- filter_at(tmpt,vars('cond_char'), any_vars(. %in% flat_speeds[sj]));
        gidone <- vector(mode="numeric")
        if (!any(match(sidone,sj,nomatch=FALSE))) {
          for (gi in 1:length(groups)) {
            tgi <- filter_at(tsi,vars('group_char'), any_vars(. %in% groups[gi]));
            for (gj in 1:length(groups)) {
              tgj <- filter_at(tsj,vars('group_char'), any_vars(. %in% groups[gj]));
              if (!any(match(gidone,gj,nomatch=FALSE))) {
                if ((gi==gj && si!=sj) || (gi!=gj && si==sj) || (gi!=gj && si!=sj)) {
                  cat("## EEG Measure: ",eeg_measures[mi]," Speed1: ",flat_speeds[si]," Speed2: ",flat_speeds[sj]," Group1: ",groups[gi]," Group2: ",groups[gj],"\n");
                  t_out <- t.test(tgi[[eeg_measures[mi]]],tgj[[eeg_measures[mi]]],alternative = c("two.sided"),
                    mu = 0, paired = FALSE, var.equal = FALSE,
                    conf.level = 0.95)
                  print(t_out)
                }
              }
            }
          gidone <- append(gidone, gi);
          }
        }
      }
      sidone <- append(sidone, si);
    }
  }
}
)
```