%   Project Title: MIM YOUNGER AND OLDER ADULTS KINEMATICS-EEG ANALYSIS
%
%   Code Designer: Jacob salminen
%## SBATCH (SLURM KICKOFF SCRIPT)
% sbatch /blue/dferris/jsalminen/GitHub/par_EEGProcessing/src/2_STUDY/mim_yaoa_speed_kin/.sh

%{
%## RESTORE MATLAB
% WARNING: restores default pathing to matlab 
restoredefaultpath;
clc;
close all;
clearvars
%}
%% SET WORKSPACE ======================================================= %%
% opengl('dsave', 'software') % might be needed to plot dipole plots?
%## TIME
tic
ADD_CLEANING_SUBMODS = false;
%## Determine Working Directories
if ~ispc
    try
        SCRIPT_DIR = matlab.desktop.editor.getActiveFilename;
        SCRIPT_DIR = fileparts(SCRIPT_DIR);
        SRC_DIR = fileparts(SCRIPT_DIR); % change this if in sub folder
    catch e
        fprintf('ERROR. PWD_DIR couldn''t be set...\n%s',getReport(e))
        % SRC_DIR = getenv('STUDY_DIR');
        SCRIPT_DIR = getenv('SCRIPT_DIR');
        SRC_DIR = getenv('SRC_DIR');
    end
else
    try
        SCRIPT_DIR = matlab.desktop.editor.getActiveFilename;
        SCRIPT_DIR = fileparts(SCRIPT_DIR);
    catch e
        fprintf('ERROR. PWD_DIR couldn''t be set...\n%s',getReport(e))
        SCRIPT_DIR = dir(['.' filesep]);
        SCRIPT_DIR = SCRIPT_DIR(1).folder;
    end
    SRC_DIR = fileparts(SCRIPT_DIR); % change this if in sub folder
end
%## Add Study, Src, & Script Paths
addpath(SCRIPT_DIR);
addpath(SRC_DIR);
cd(SRC_DIR);
fprintf(1,'Current folder: %s\n',SRC_DIR);
%## Set PWD_DIR, EEGLAB path, _functions path, and others...
set_workspace
%% (DATASET INFORMATION) =============================================== %%
% [SUBJ_PICS,GROUP_NAMES,SUBJ_ITERS,~,~,~,~] = mim_dataset_information('yaoa_spca_speed');
[SUBJ_PICS,GROUP_NAMES,SUBJ_ITERS,~,~,~,~] = mim_dataset_information('yaoa_spca_speed');
%% (PATHS) ============================================================= %%
%-- colors
colormap(linspecer);
%- datset name
DATA_SET = 'MIM_dataset';
%- study name
STUDY_DNAME = '04232024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej';
% STUDY_FNAME = 'kin_eeg_epoch_study';
% studies_fpath = [PATHS.data_dir filesep DATA_SET filesep '_studies'];
%- load study file
% study_fpath = [studies_fpath filesep sprintf('%s',STUDY_DNAME)];
%- override
study_fpath = ['R:\Ferris-Lab\jsalminen\Experiments_Data\MIND_IN_MOTION_PRJ\mim_proc_figs_saves' filesep STUDY_DNAME];
%- load cluster
CLUSTER_K = 11;
CLUSTER_STUDY_NAME = 'temp_study_rejics5';
cluster_fpath = [study_fpath filesep 'iclabel_cluster_kmeansalt_rb3'];
cluster_study_fpath = [cluster_fpath filesep 'icrej_5'];
cluster_k_dir = [cluster_study_fpath filesep sprintf('%i',CLUSTER_K)];
%- save directory 
save_dir = [study_fpath filesep 'behavioral_data'];
if ~exist(save_dir,'dir')
    mkdir(save_dir);
end
%% ===================================================================== %%
%## LOAD STUDY
if ~ispc
    tmp = load('-mat',[cluster_study_fpath filesep sprintf('%s_UNIX.study',CLUSTER_STUDY_NAME)]);
    STUDY = tmp.STUDY;
else
    tmp = load('-mat',[cluster_study_fpath filesep sprintf('%s.study',CLUSTER_STUDY_NAME)]);
    STUDY = tmp.STUDY;
end
%##
% [SUBJ_PICS,GROUP_NAMES,SUBJ_ITERS,~,~,~,~] = mim_dataset_information('yaoa_spca');
% [SUBJ_PICS,GROUP_NAMES,SUBJ_ITERS,~,~,~,~] = mim_dataset_information('yaoa_mri_study');
%- override with already processed ALLEEG set
SUBJ_PICS = cell(1,length(GROUP_NAMES));
SUBJ_ITERS = cell(1,length(GROUP_NAMES));
for i = 1:length(STUDY.datasetinfo)
    gi = find(strcmp(STUDY.datasetinfo(i).group,GROUP_NAMES));
    SUBJ_PICS{1,gi} = [SUBJ_PICS{1,gi}, {STUDY.datasetinfo(i).subject}];
    if isempty(SUBJ_ITERS{1,gi})
        SUBJ_ITERS{1,gi} = 1;
    else
        SUBJ_ITERS{1,gi} = [SUBJ_ITERS{1,gi}, SUBJ_ITERS{1,gi}(end)+1];
    end
end

%% (LOAD IF AVAILABLE) ================================================= %%
% save_dir = [studies_fpath filesep study_dir_name filesep 'behavioral_data'];
table_new_ls = load([save_dir filesep 'ls_table_meantrial.mat']);
table_new_ls = table_new_ls.table_new_ls;
table_new_imu = load([save_dir filesep 'imu_table_meantrial.mat']);
table_new_imu = table_new_imu.table_new_imu;
%% (STATS STRUCT) ====================================================== %%
DESIGN_TABLE_VAR = 'mean_design_id';
GROUP_TABLE_VAR = 'mean_group_id';
%## PLOT ============================================================ %%
%## VISUAL
%- colors
COLOR_MAPS_TERRAIN = linspecer(4);
YELLOW = [254,223,0]/255;
COLOR_MAPS_TERRAIN = [COLOR_MAPS_TERRAIN(3,:);YELLOW;COLOR_MAPS_TERRAIN(4,:);COLOR_MAPS_TERRAIN(2,:)];
COLOR_MAPS_SPEED = linspecer(4*3);
COLOR_MAPS_SPEED = [COLOR_MAPS_SPEED(1,:);COLOR_MAPS_SPEED(2,:);COLOR_MAPS_SPEED(3,:);COLOR_MAPS_SPEED(4,:)];
%-
IM_RESIZE = 1.1;
AX_H  = 0.2;
AX_W = 0.275;
AX_HORIZ_SHIFT = 0.1;
AX_INIT_HORIZ = 0.08;
AX_INIT_VERT = 0.6;
AX_VERT_SHIFT = 0.125;
%-
GROUP_LAB_FONTSIZE = 10;
XLAB_FONTSIZE = 10;
YLAB_FONTSIZE = 10;
XTICK_FONTSIZE = 7;
TITLE_FONTSIZE = 10;
FONT_SIZE_VIO = 10;
FONT_SIZE_VIO_REG = 7;
%-
FONT_NAME = 'Arial';
GROUP_LAB_FONTWEIGHT = 'bold ';
XLAB_FONTWEIGHT = 'bold';
YLAB_FONTWEIGHT = 'bold';
TITLE_FONTWEIGHT = 'bold';
%-
LAB_A_YOFFSET = -0.1;
LAB_A_XOFFSET = -0.125;
LAB_B_YOFFSET = 0.12;
LAB_B_XOFFSET = -0.12;
LAB_C_YOFFSET = 0.12;
LAB_C_XOFFSET = -0.12;
LAB_D_YOFFSET = 0.12;
LAB_D_XOFFSET = -0.12;
XLABEL_OFFSET = -.05;
FIGURE_POSITION =[0,0,6.5,9];
VIOLIN_STRUCT = struct('Width',0.1,...
    'ShowWhiskers',false,...
    'ShowNotches',false,...
    'ShowBox',true,...
    'ShowMedian',true,...
    'Bandwidth',0.15,...
    'QuartileStyle','shadow',...
    'HalfViolin','full',...
    'DataStyle','scatter',...
    'MarkerSize',8,...
    'EdgeColor',[0.5,0.5,0.5],...
    'ViolinAlpha',{{0.2 0.3}},...
    'do_plot_outlier_marks',true,...
    'use_raw_bandwidth',false);
PLOT_STRUCT = struct('color_map',[],...
    'cond_labels',{{'0.25','0.50','0.75','1.0'}},...
    'cond_offsets',[-0.35,-0.1,0.15,0.40],...
    'group_labels',{{'YA','OHFA','OLFA'}},...
    'group_offsets',[0.125,0.475,0.812],...
    'group_lab_yoffset',-0.275,...
    'group_lab_fontweight','normal',...
    'group_lab_fontsize',10,...
    'y_label','unit',...
    'y_label_fontsize',10,...
    'y_label_fontweight','bold',...
    'ylim',[],...
    'x_label','Speed (m/s)',...
    'x_label_fontsize',10,...
    'x_label_fontweight','bold',...
    'x_label_yoffset',-.05,...
    'xlim',[],...
    'title','',...
    'title_fontsize',10,...
    'title_fontweight','bold',...
    'font_size',10,...
    'font_name','Arial',...
    'do_combine_groups',false,...
    'ax_position',[0,0,1,1],...
    'ax_line_width',1);
BRACKET_STRUCT = struct('sig_sign','+',...
    'line_specs',{{'LineStyle','-','LineWidth',1,'Color','k'}},...
    'text_specs',{{'FontSize',10,'FontName','Arial','FontWeight','bold'}},...
    'bracket_conn',[],...
    'conn_offset_y_upper',[],...
    'bracket_offset_y_upper',0,...
    'bracket_offset_y_lower',0,...
    'sig_offset_x',0,...
    'sig_offset_y',[]);
SIGLINE_STRUCT = struct('sig_sign','*',...
    'line_specs',{{'LineStyle','-','LineWidth',2,'Color','k'}},...
    'text_specs',{{'FontSize',10,'FontName','Arial','FontWeight','bold'}},...
    'conn_y',[],...
    'conn_offset_y',[],...
    'sig_offset_x',0,...
    'sig_offset_y',0); 
AXES_DEFAULT_PROPS = {'box','off','xtick',[],'ytick',[],...
    'ztick',[],'xcolor',[1,1,1],'ycolor',[1,1,1]};
%## FACTORS
meas_names = {'mean_APexc_COV','mean_MLexc_COV','mean_StepDur_cov','mean_og_mean_ms'};
meas_ylabel = {'COV (%)','COV (%)','COV (%)','Walking Speed (m/s)'};
meas_titles = {{'Anteroposterior Excursion';'Coefficient of Variation'},...
    {'Mediolateral Excursion';'Coefficient of Variation'},...
    {'Step Duration';'Coefficient of Variation'},...
    {'Overground Walking';'Speeds'}};
xtick_label_g = {'0.25','0.50','0.75','1.0'};
YLIM = {[0,65],[0,45],[0,22.5],[0,2.35]};
speed_xvals = (0:5)*0.25;
% cnts = 1;
%% FIGURE INIT
%-- temps
horiz_shift = 0;
vert_shift = 0;
%-- figure props
fig = figure('color','white', ...
    'Renderer','Painters');
set(fig,'Units','inches', ...
    'Position',FIGURE_POSITION, ...
    'PaperUnits','inches', ...
    'PaperSize',[1 1], ...
    'PaperPosition',[0 0 1 1])
p_sz = get(fig,'Position');
set(gca,AXES_DEFAULT_PROPS{:});
hold on;
%% (SPEED) OG SPEEDS - MAIN EFFECTS ================================ %%
meas_i = 4;
des_i = 1;
conds_keep = {1};
%-
tmp = (cellfun(@(x) table_new_ls.trial_tag_in == categorical(x),conds_keep,'UniformOutput',false));
tmp = any(cat(2,tmp{:}),2);
inds = table_new_ls.(DESIGN_TABLE_VAR) == des_i & tmp;
tmp_table = table_new_ls(inds,:);
tmp_table = table(categorical(string(tmp_table.trial_char)),categorical(double(tmp_table.trial_tag_in)),...
    categorical(string(tmp_table.subj_char)),...
    categorical(string(tmp_table.(GROUP_TABLE_VAR))),tmp_table.(meas_names{meas_i}),...
    'VariableNames',{'trial_char','trial_tag_in','subj_char',GROUP_TABLE_VAR,meas_names{meas_i}});
tmp_table(tmp_table.(meas_names{meas_i}) == 0,:) = [];
tmp_table(isnan(tmp_table.(meas_names{meas_i})),:) = [];
tmp_table(isinf(tmp_table.(meas_names{meas_i})),:) = [];

%## PLOT =============================================================== %%
anvg = 1.447e-05;
gF = 12.874;
%- fdr corrected
adj_p = [0.3795,0.00001,0.0027];
multi_comp_pairs = [1,2;1,3;2,3];
cis = cat(3,[1.007,1.21],[0.891,1.12],[0.614,0.841]);
cis = permute(cis,[3,1,2]);
anvs = 0; %t{2,7};
chkl = find((anvs <= [0.05,0.01,0.001]),1,'last');
if ~isempty(chkl)
    ast = sprintf('^{%s}',repmat('*',[1,chkl]));
end
str = {sprintf('%s F=%0.2g',ast,gF),...
    '',...
    ''};
CONFINT_STRUCT = struct('do_display',true, ...
        'y_bnds',cis, ...
        'x_vals',repmat(0,[3,1]), ...
        'errbar_struct',struct('line_specs',{{'LineStyle','-','LineWidth',2,'Color','k'}}, ...
            'err_bar_width',0.1));
tssc = struct('var_type','continuous', ...
    'anova',1, ...
    'multc_pvals',[],...
    'multc_pvals_pairs',[],...
    'regress_line',[], ... 
    'line_type',{'best_fit'},... % ('best_fit' | 'means') % continuous predictors
    'regress_xvals',[],... % continuous predictors
    'order',{{}});
tssg = struct('var_type','categorical', ...
    'anova',anvg, ...
    'multc_pvals',[adj_p],...
    'multc_pvals_pairs',[multi_comp_pairs],...
    'regress_line',[],... 
    'line_type',{'best_fit'},... % ('best_fit' | 'means') % continuous predictors
    'regress_xvals',0,... % continuous predictors
    'order',{{}});
STATS_STRUCT = struct('sig_levels',[0.05,0.01,0.001],...
    'cond_stats',tssc, ...
    'group_stats',tssg, ...
    'stats_char',struct('str',{str}, ...
        'offsets',[-0.1,-0.05], ...
        'font_size',7, ...
        'do_display',true));
%-
PLOT_STRUCT.color_map = COLOR_MAPS_TERRAIN;
PLOT_STRUCT.cond_labels = {''};
PLOT_STRUCT.title = meas_titles{meas_i}; %title_plot{meas_i};
PLOT_STRUCT.y_label = meas_ylabel{meas_i};
PLOT_STRUCT.x_label = '';
PLOT_STRUCT.group_offsets = [-0.5,-0.5*2,-0.5*3];
PLOT_STRUCT.cond_offsets = 0;
PLOT_STRUCT.xlim = [0.2,1.8];
PLOT_STRUCT.ylim = YLIM{meas_i};
PLOT_STRUCT.group_lab_yoffset = -.1;
PLOT_STRUCT.ax_position = [AX_INIT_HORIZ+horiz_shift,AX_INIT_VERT+vert_shift,AX_W*IM_RESIZE,AX_H*IM_RESIZE];  %[left bottom width height]
%##
BRACKET_STRUCT.conn_offset_y_upper = [0,0.2,0.2];
ax = axes();
ax = group_violin(tmp_table,meas_names{meas_i},'trial_tag_in',GROUP_TABLE_VAR,...
    ax,...
    'VIOLIN_STRUCT',VIOLIN_STRUCT,...
    'PLOT_STRUCT',PLOT_STRUCT,...
    'STATS_STRUCT',STATS_STRUCT,...
    'SIGLINE_STRUCT',SIGLINE_STRUCT,...
    'BRACKET_STRUCT',BRACKET_STRUCT, ...
    'CONFINT_STRUCT',CONFINT_STRUCT);
%--
annotation('textbox',[AX_INIT_HORIZ+LAB_D_XOFFSET+(0.1/2)+horiz_shift,AX_INIT_VERT+vert_shift+LAB_B_YOFFSET+(0.1/2),.1,.1],...
    'String','A)','HorizontalAlignment','left',...
    'VerticalAlignment','top','LineStyle','none','FontName',FONT_NAME,...
    'FontSize',14,'FontWeight','Bold','Units','normalized');
%## SHIFT
horiz_shift = horiz_shift + AX_W*IM_RESIZE + AX_HORIZ_SHIFT*IM_RESIZE;
%% (SPEED) ML COV - MAIN EFFECTS ======================================= %%
meas_i = 2;
des_i = 2;
%-
inds = table_new_imu.(DESIGN_TABLE_VAR) == des_i;
tmp_table = table_new_imu(inds,:);
tmp_table = table(double(string(tmp_table.trial_char)),categorical(string(tmp_table.subj_char)),...
    categorical(string(tmp_table.(GROUP_TABLE_VAR))),tmp_table.(meas_names{meas_i}),...
    'VariableNames',{'trial_char','subj_char',GROUP_TABLE_VAR,meas_names{meas_i}});
%## PLOT =============================================================== %%
R2 = 0.4973;
anvs = 0.0001;
anvg = 0.017;
anvin = 0.003;
adj_p = [0.8071,0.8948,0.9812];
multi_comp_pairs = [1,2;1,3;2,3];
%--
cis = cat(3,[13.37,15.81],[12.7,15.3],[12.96,15.44]);
cis = permute(cis,[3,1,2]);
%-- mod coeffs
int = 11.12634;
tm = 5.53992;
gint1 = -3.39468;
gint2 = 0.09723;
gm1 = 4.52826;
gm2 = -0.78165;
%## INTERACTION
chkl = find((anvs <= [0.05,0.01,0.001]),1,'last');
if ~isempty(chkl)
    ast = sprintf('^{%s}',repmat('*',[1,chkl]));
end
str = {sprintf('%sR^{2}=%0.2g\n(%0.2g)x+(%0.2g)',ast,R2,tm,int),...
    sprintf('\n(%0.2g)x+(%0.2g)',tm+gm1,int+gint1),...
    sprintf('\n(%0.2g)x+(%0.2g)',tm+gm2,int+gint2)};
CONFINT_STRUCT = struct('do_display',true, ...
        'y_bnds',cis, ...
        'x_vals',repmat(0,[3,1]), ...
        'errbar_struct',struct('line_specs',{{'LineStyle','-','LineWidth',2,'Color','k'}}, ...
            'err_bar_width',0.1));
tssc = struct('var_type','continuous', ...
    'anova',anvs, ...
    'multc_pvals',[],...
    'multc_pvals_pairs',[],...
    'regress_line',[[int,tm];...
        [int+gint1,tm+gm1];...
        [int+gint2,tm+gm2]], ... 
    'line_type',{'best_fit'},... % ('best_fit' | 'means') % continuous predictors
    'regress_xvals',(0:5)*0.25,... % continuous predictors
    'order',{{}});
tssg = struct('var_type','categorical', ...
    'anova',anvin, ...
    'multc_pvals',[adj_p],...
    'multc_pvals_pairs',[multi_comp_pairs],...
    'regress_line',[],... 
    'line_type',{'best_fit'},... % ('best_fit' | 'means') % continuous predictors
    'regress_xvals',0,... % continuous predictors
    'order',{{}});
STATS_STRUCT = struct('sig_levels',[0.05,0.01,0.001],...
    'cond_stats',tssc, ...
    'group_stats',tssg, ...
    'stats_char',struct('str',{str}, ...
        'offsets',[-0.1,0], ...
        'font_size',7, ...
        'do_display',true));
%##
PLOT_STRUCT.color_map = COLOR_MAPS_SPEED;
PLOT_STRUCT.cond_labels = xtick_label_g;
PLOT_STRUCT.title = meas_titles{meas_i}; %title_plot{meas_i};
PLOT_STRUCT.y_label = meas_ylabel{meas_i};
PLOT_STRUCT.x_label = 'Speed (m/s)';
PLOT_STRUCT.x_label_yoffset = -0.13;
PLOT_STRUCT.group_offsets = [0.125,0.475,0.812];
PLOT_STRUCT.cond_offsets = [-0.35,-0.1,0.15,0.40];
PLOT_STRUCT.xlim = [];
PLOT_STRUCT.ylim = YLIM{meas_i};
PLOT_STRUCT.group_lab_yoffset = -.22;
PLOT_STRUCT.ax_position = [AX_INIT_HORIZ+horiz_shift,AX_INIT_VERT+vert_shift,AX_W*IM_RESIZE,AX_H*IM_RESIZE];  %[left bottom width height]
%##
BRACKET_STRUCT.conn_offset_y_upper = [1.5,5,0];
%##
ax = axes();
ax = group_violin(tmp_table,meas_names{meas_i},'trial_char',GROUP_TABLE_VAR,...
    ax,...
    'VIOLIN_STRUCT',VIOLIN_STRUCT,...
    'PLOT_STRUCT',PLOT_STRUCT,...
    'STATS_STRUCT',STATS_STRUCT,...
    'SIGLINE_STRUCT',SIGLINE_STRUCT,...
    'BRACKET_STRUCT',BRACKET_STRUCT, ...
    'CONFINT_STRUCT',CONFINT_STRUCT);
%- 
annotation('textbox',[AX_INIT_HORIZ+LAB_C_XOFFSET+(0.1/2)+horiz_shift,AX_INIT_VERT+vert_shift+LAB_C_YOFFSET+(0.1/2),.1,.1],...
    'String','B)','HorizontalAlignment','left',...
    'VerticalAlignment','top','LineStyle','none','FontName',FONT_NAME,...
    'FontSize',14,'FontWeight','Bold','Units','normalized');
%## SHIFT
horiz_shift = 0;
vert_shift = vert_shift - AX_H*IM_RESIZE - AX_VERT_SHIFT*IM_RESIZE;
% horiz_shift = horiz_shift + AX_W*IM_RESIZE + AX_HORIZ_SHIFT*IM_RESIZE;
%% (SPEED) STEP DUR. COV - MAIN EFFECTS ================================ %%
meas_i = 3;
des_i = 2;
%-
inds = table_new_ls.(DESIGN_TABLE_VAR) == des_i;
tmp_table = table_new_ls(inds,:);
tmp_table = table(double(string(tmp_table.trial_char)),categorical(string(tmp_table.subj_char)),...
    categorical(string(tmp_table.(GROUP_TABLE_VAR))),tmp_table.(meas_names{meas_i}),...
    'VariableNames',{'trial_char','subj_char',GROUP_TABLE_VAR,meas_names{meas_i}});
%## PLOT =============================================================== %%
%-
r2m = 0.4246003;
r2c = 0.5767898;
f2m = 0.7379;
f2c = 1.3629;
%*
R2 = r2c;
%-
anvs =  2e-16;
anvg =  0.5054;
%--
cis = cat(3,[4.72,5.61],[4.94,5.90],[5.076,5.984]);
cis = permute(cis,[3,1,2]);
%-
int = 8.7317;
tm = -5.7030;
gint1 = 0.2586;
gint2 = 0.3634;
%## MAIN EFFECTS
coeffs = {[int,tm],...
        [int+gint1,tm],...
        [int+gint2,tm]};
chkl = find((anvs <= [0.05,0.01,0.001]),1,'last');
if ~isempty(chkl)
    ast = sprintf('^{%s}',repmat('*',[1,chkl]));
end
str = {sprintf('%sR^2=%0.2g\nm=%0.2g',ast,R2,tm),...
    sprintf('b_{YA}=%0.2g  b_{OHFA}=%0.2g  b_{OLFA}=%0.2g\n',int,int+gint1,int+gint2),...
    ''};
CONFINT_STRUCT = struct('do_display',true, ...
        'y_bnds',cis, ...
        'x_vals',repmat(0,[3,1]), ...
        'errbar_struct',struct('line_specs',{{'LineStyle','-','LineWidth',2,'Color','k'}}, ...
            'err_bar_width',0.1));
tssc = struct('var_type','continuous', ...
    'anova',anvs, ...
    'multc_pvals',[],...
    'multc_pvals_pairs',[],...
    'regress_line',[[int,tm];...
        [int+gint1,tm];...
        [int+gint2,tm]], ... 
    'line_type',{'best_fit'},... % ('best_fit' | 'means') % continuous predictors
    'regress_xvals',(0:5)*0.25,... % continuous predictors
    'order',{{}});
tssg = struct('var_type','categorical', ...
    'anova',anvg, ...
    'multc_pvals',[adj_p],...
    'multc_pvals_pairs',[multi_comp_pairs],...
    'regress_line',[],... 
    'line_type',{'best_fit'},... % ('best_fit' | 'means') % continuous predictors
    'regress_xvals',0,... % continuous predictors
    'order',{{}});
STATS_STRUCT = struct('sig_levels',[0.05,0.01,0.001],...
    'cond_stats',tssc, ...
    'group_stats',tssg, ...
    'stats_char',struct('str',{str}, ...
        'offsets',[-0.1,0], ...
        'font_size',7, ...
        'do_display',true));
%##
PLOT_STRUCT.color_map = COLOR_MAPS_SPEED;
PLOT_STRUCT.cond_labels = xtick_label_g;
PLOT_STRUCT.title = meas_titles{meas_i}; %title_plot{meas_i};
PLOT_STRUCT.y_label = meas_ylabel{meas_i};
PLOT_STRUCT.x_label = 'Speed (m/s)';
PLOT_STRUCT.x_label_yoffset = -0.13;
PLOT_STRUCT.group_offsets = [0.125,0.475,0.812];
PLOT_STRUCT.cond_offsets = [-0.35,-0.1,0.15,0.40];
PLOT_STRUCT.xlim = [];
PLOT_STRUCT.ylim = YLIM{meas_i};
PLOT_STRUCT.group_lab_yoffset = -.22;
PLOT_STRUCT.ax_position = [AX_INIT_HORIZ+horiz_shift,AX_INIT_VERT+vert_shift,AX_W*IM_RESIZE,AX_H*IM_RESIZE];  %[left bottom width height]
%##
BRACKET_STRUCT.conn_offset_y_upper = [0,0.2,0.2];
%##
ax = axes();
ax = group_violin(tmp_table,meas_names{meas_i},'trial_char',GROUP_TABLE_VAR,...
    ax,...
    'VIOLIN_STRUCT',VIOLIN_STRUCT,...
    'PLOT_STRUCT',PLOT_STRUCT,...
    'STATS_STRUCT',STATS_STRUCT,...
    'SIGLINE_STRUCT',SIGLINE_STRUCT,...
    'BRACKET_STRUCT',BRACKET_STRUCT, ...
    'CONFINT_STRUCT',CONFINT_STRUCT);
%## LETTER
annotation('textbox',[AX_INIT_HORIZ+LAB_C_XOFFSET+(0.1/2)+horiz_shift,AX_INIT_VERT+vert_shift+LAB_B_YOFFSET+(0.1/2),.1,.1],...
    'String','C)','HorizontalAlignment','left',...
    'VerticalAlignment','top','LineStyle','none','FontName',FONT_NAME,...
    'FontSize',14,'FontWeight','Bold','Units','normalized');
%## SAVE
exportgraphics(fig,[save_dir filesep 'figure_behavioral_data_paper_anova_rdata.tiff'],'Resolution',1000);
exportgraphics(fig,[save_dir filesep 'figure_behavioral_data_paper_anova_rdata.pdf'],'ContentType','vector');