%   Project Title: MIM YOUNGER AND OLDER ADULTS KINEMATICS-EEG ANALYSIS
%
%   Code Designer: Jacob salminen
%## SBATCH (SLURM KICKOFF SCRIPT)
% sbatch /blue/dferris/jsalminen/GitHub/par_EEGProcessing/src/2_STUDY/mim_yaoa_speed_kin/.sh

%{
%## RESTORE MATLAB
% WARNING: restores default pathing to matlab 
restoredefaultpath;
clc;
close all;
clearvars
%}
%% SET WORKSPACE ======================================================= %%
% opengl('dsave', 'software') % might be needed to plot dipole plots?
%## TIME
tic
ADD_CLEANING_SUBMODS = false;
%## Determine Working Directories
if ~ispc
    try
        SCRIPT_DIR = matlab.desktop.editor.getActiveFilename;
        SCRIPT_DIR = fileparts(SCRIPT_DIR);
        SRC_DIR = fileparts(SCRIPT_DIR); % change this if in sub folder
    catch e
        fprintf('ERROR. PWD_DIR couldn''t be set...\n%s',getReport(e))
        % SRC_DIR = getenv('STUDY_DIR');
        SCRIPT_DIR = getenv('SCRIPT_DIR');
        SRC_DIR = getenv('SRC_DIR');
    end
else
    try
        SCRIPT_DIR = matlab.desktop.editor.getActiveFilename;
        SCRIPT_DIR = fileparts(SCRIPT_DIR);
    catch e
        fprintf('ERROR. PWD_DIR couldn''t be set...\n%s',getReport(e))
        SCRIPT_DIR = dir(['.' filesep]);
        SCRIPT_DIR = SCRIPT_DIR(1).folder;
    end
    SRC_DIR = fileparts(SCRIPT_DIR); % change this if in sub folder
end
%## Add Study, Src, & Script Paths
addpath(SCRIPT_DIR);
addpath(SRC_DIR);
cd(SRC_DIR);
fprintf(1,'Current folder: %s\n',SRC_DIR);
%## Set PWD_DIR, EEGLAB path, _functions path, and others...
set_workspace
%% (DATASET INFORMATION) =============================================== %%
% [SUBJ_PICS,GROUP_NAMES,SUBJ_ITERS,~,~,~,~] = mim_dataset_information('yaoa_spca');
[SUBJ_PICS,GROUP_NAMES,SUBJ_ITERS,~,~,~,~] = mim_dataset_information('yaoa_spca_speed');
%% (PARAMETERS) ======================================================== %%

%% (PATHS) ============================================================= %%
%- datset name
DATA_SET = 'MIM_dataset';
%- study name
% STUDY_DNAME = '10172024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej_speed';
% STUDY_FNAME = 'kin_eeg_epoch_study';
% studies_fpath = [PATHS.src_dir filesep '_data' filesep DATA_SET filesep '_studies'];
%- load study file
% study_fpath = [studies_fpath filesep sprintf('%s',STUDY_DNAME)];
%- override
study_fpath = 'R:\Ferris-Lab\jsalminen\Experiments_Data\MIND_IN_MOTION_PRJ\mim_proc_figs_saves\04232024_MIM_YAOAN89_antsnorm_dipfix_iccREMG0p4_powpow0p3_skull0p01_15mmrej';
%- load cluster
CLUSTER_K = 11;
CLUSTER_STUDY_NAME = 'temp_study_rejics5';
cluster_fpath = [study_fpath filesep 'iclabel_cluster_kmeansalt_rb3'];
cluster_study_fpath = [cluster_fpath filesep 'icrej_5'];
cluster_k_dir = [cluster_study_fpath filesep sprintf('%i',CLUSTER_K)];
%- save directory 
ANALYSIS_DNAME = ['psd_calcs' filesep 'group_spec' filesep 'split_band_test'];
save_dir = [cluster_k_dir filesep ANALYSIS_DNAME];
if ~exist(save_dir,'dir')
    mkdir(save_dir);
end
%% ===================================================================== %%
%## LOAD STUDY
if ~ispc
    tmp = load('-mat',[cluster_study_fpath filesep sprintf('%s_UNIX.study',CLUSTER_STUDY_NAME)]);
    STUDY = tmp.STUDY;
else
    tmp = load('-mat',[cluster_study_fpath filesep sprintf('%s.study',CLUSTER_STUDY_NAME)]);
    STUDY = tmp.STUDY;
end
%-
cl_struct = par_load(cluster_k_dir,sprintf('cl_inf_%i.mat',CLUSTER_K));
STUDY.cluster = cl_struct;
[comps_out,main_cl_inds,outlier_cl_inds] = eeglab_get_cluster_comps(STUDY);
CLUSTER_PICS = main_cl_inds;
%-
save_dir = [cluster_k_dir filesep ANALYSIS_DNAME];
if ~exist(save_dir,'dir')
    mkdir(save_dir);
end
%% (LOAD STATISTICS & DATA EXCEL SHEET FROM R) ========================= %%
%-
tmp_dir = [cluster_k_dir];
sppb_table = readtable('M:\jsalminen\GitHub\MIND_IN_MOTION_PRJ\_data\MIM_dataset\_studies\subject_mgmt\sppb_analysis.xlsx', ...
    "FileType","spreadsheet","UseExcel",true);

%## MANUAL ENTRY
reject_table = readtable('M:\jsalminen\GitHub\MIND_IN_MOTION_PRJ\_data\MIM_dataset\_studies\subject_mgmt\subject_errors_yaoa_speed_eegout_10152024.xlsx', ...
    "Sheet","subj_err_sppb_03172025","FileType","spreadsheet","UseExcel",true);
subj_cat_chars = {'all conds','missing conds','other'};
not_all_cond_subjs = {'H3024','H3046','H3047','H3053','H3063','H3073', ...
    'H3092','NH3006','NH3007','NH3023','NH3025','NH3028','NH3051','NH3056','NH3071',...
    'NH3082','NH3123'};
all_conds_subjs = {STUDY.datasetinfo.subject};
% sppb_table.condition_status = categorical(repmat({''},size(sppb_table,1),1));
sppb_table.condition_status = cell(size(sppb_table,1),1);
for i = 1:size(sppb_table,1)
    if any(strcmp(sppb_table.subject_code(i),all_conds_subjs))
        sppb_table.condition_status{i} = 'all conditions';
    elseif any(strcmp(sppb_table.subject_code(i),not_all_cond_subjs))
        sppb_table.condition_status{i} = 'missing conditions';
    elseif any(strcmp(sppb_table.subject_code(i),reject_table.subject_name))
        sppb_table.condition_status{i} = 'other reject';
    else
        sppb_table.condition_status{i} = 'not considered';
    end
end
% inds = sppb_table.condition_status == categorical({'all conditions'}) | ...
%     sppb_table.condition_status == categorical({'missing conditions'}) | ...
%     sppb_table.condition_status == categorical({'other reject'});
%-- test 3 group
% inds = (sppb_table.condition_status == categorical({'all conditions'}) | ...
%     sppb_table.condition_status == categorical({'missing conditions'}) | ...
%     sppb_table.condition_status == categorical({'other reject'})) & ...
%     any(sppb_table.group_code == [2,3],2);
% COND_OFFSETS = [-0.01,0,0.01];
% XLIM = [0.98,1.02];
% multc_pairs = cat(3,[[1,1];[1,2]],[[1,1];[1,3]],[[1,2];[1,3]]);
% multc_pairs = permute(multc_pairs,[3,1,2]);

%-- test 2 group
inds = (sppb_table.condition_status == categorical({'all conditions'}) | ...
    sppb_table.condition_status == categorical({'missing conditions'})) & ...
    any(sppb_table.group_code == [2,3],2);
COND_OFFSETS = [-0.01,0.01];
XLIM = [0.975,1.025];
% multc_pairs = cat(3,[1,1],[1,2]);
multc_pairs = [];
subj_cat_chars = {'Included','Excluded'};
%-- 
sppb_table = sppb_table(inds,:);
sppb_table.condition_status = categorical(sppb_table.condition_status);

%% ===================================================================== %%
%## PARAMETERS
cmaps_speed = linspecer(3);
%-
SAVE_RES = 300;
TITLE_TXT_SIZE = 14;
IM_RESIZE = 1.3;
AX_W = 0.4;
AX_H = 0.25;
AX_FONT_NAME = 'Arial';
AX_X_SHIFT = 1.2;
AX_Y_SHIFT = 1.55;
AX_INIT_X = 0.1;
AX_INIT_Y = 0.6;
%## 
AXES_DEFAULT_PROPS = {'box','off', ...
    'xtick',[], ...
    'ytick',[],...
    'ztick',[], ...
    'xcolor',[1,1,1], ...
    'ycolor',[1,1,1]};
%## VIOLIN PLOTS
PLOT_STRUCT = struct('color_map',cmaps_speed,...
    'cond_labels',{subj_cat_chars},... 
    'cond_offsets',COND_OFFSETS,...
    'do_group_labels',false, ...
    'group_labels',{{}},...
    'group_offsets',0,...
    'group_lab_yoffset',-0.1,...
    'group_lab_fontweight','normal',...
    'group_lab_fontsize',10,...
    'y_label','SPPB Score Total',...
    'y_label_fontsize',12,...
    'y_label_fontweight','bold',...
    'ylim',[],...
    'x_label','',...
    'x_label_fontsize',12,...
    'x_label_fontweight','bold',...
    'x_label_yoffset',-0.05,...
    'xlim',XLIM,...
    'title',{{'Older Adult','SPPB Score Comparison'}},...
    'title_fontsize',10,...
    'title_fontweight','bold',...
    'font_size',12,...
    'font_name','Arial',...
    'do_combine_groups',true,...
    'ax_position',[0,0,1,1],...
    'ax_line_width',1,...
    'xtick_angle',0);
VIOLIN_STRUCT = struct('Width',0.005,...
    'ShowWhiskers',false,...
    'ShowNotches',false,...
    'ShowBox',true,...
    'ShowMedian',true,...
    'Bandwidth',0.15,...
    'QuartileStyle','shadow',...
    'HalfViolin','full',...
    'DataStyle','scatter',...
    'MarkerSize',8,...
    'EdgeColor',[0.5,0.5,0.5],...
    'ViolinAlpha',{{0.2 0.3}},...
    'do_plot_outlier_marks',true,...
    'use_raw_bandwidth',false);
DEF_BRACKET_STRUCT = struct('sig_sign','+',...
    'line_specs',{{'LineStyle','-','LineWidth',2,'Color','k'}},...
    'text_specs',{{'FontSize',10,'FontName','Arial','FontWeight','bold'}},...
    'bracket_conn',[],...
    'conn_offset_y_upper',[],...
    'bracket_offset_y_upper',0,...
    'bracket_offset_y_lower',0,...
    'sig_offset_x',0,...
    'sig_offset_y',[]);
DEF_SIGLINE_STRUCT = struct('sig_sign','*',...
    'line_specs',{{'LineStyle','-','LineWidth',2,'Color','k'}},...
    'text_specs',{{'FontSize',12,'FontName','Arial','FontWeight','bold'}},...
    'conn_y',[],...
    'conn_offset_y',[0.5,0.5,0.5],...
    'sig_offset_x',[],...
    'sig_offset_y',0.75);
%## ===================================================================== %%
X_DIM = 1;
tmp_savedir = save_dir;
mkdir(tmp_savedir);
%## SET SHIFTS
x_cnt = 1;
y_shift = AX_INIT_Y;
x_shift = AX_INIT_X;
%## INITIATE FIGURE
fig = figure('color','white');
% sgtitle('SPPB Scores','FontName',AX_FONT_NAME,'FontSize',TITLE_TXT_SIZE,'FontWeight','bold','Interpreter','none');
set(fig, ...
    'Units','inches', ...
    'Position',[0.5,0.5,6.5,9], ...
    'PaperUnits','inches', ...
    'PaperSize',[1 1], ...
    'PaperPosition',[0 0 1 1])
hold on;
set(gca,AXES_DEFAULT_PROPS{:})

%## STATS
modo = fitlm(sppb_table,'sppb_12 ~ 1+condition_status');
anvo = anova(modo);
[p,t,anova_out,terms] = anovan([sppb_table.sppb_12],{sppb_table.condition_status},...
    'sstype',3,'varnames',{'condition_status'},'model','linear','Display','off');
[comparisons,means,~,gnames] = multcompare(anova_out,'Dimension',1,...
    'display','off','Alpha',0.05,'CriticalValueType','bonferroni'); % compaarisons columns: [pred1,pred2,lowerCI,estimate,upperCI,p-val]
disp(modo)
[h,crit_p,adj_ci_cvrg,adj_p] = fdr_bh(comparisons(:,6));
% adj_p = comparisons(:,6);

%-
if t{2,7} < 0.001
    str = '***';
elseif t{2,7} > 0.001 && t{2,7} <= 0.01
    str = '**';
elseif t{2,7} < 0.05
    str = '*';
else
    str = '';
end
str = sprintf('%sF = %0.2f\n',str,t{2,6});
cond_stats = struct('var_type','categorical', ...
    'anova',t{2,7}, ...
    'multc_pvals',adj_p,...
    'multc_pvals_pairs',multc_pairs,...
    'regress_line',[],... 
    'line_type',{'best_fit'},... % ('best_fit' | 'means') % continuous predictors
    'regress_xvals',0,... % continous indepedent variable
    'order',{{}});
group_stats = struct('var_type','numeric', ...
    'anova',1, ...
    'multc_pvals',[],...
    'multc_pvals_pairs',[],...
    'regress_line',[],... 
    'line_type',{'best_fit'},... % ('best_fit' | 'means') % continuous predictors
    'regress_xvals',0,... % continous indepedent variable
    'order',{{}});
% cond_stats.order = cellstr(string(unique(table_in.(cond_char))));
% group_stats.order = cellstr(string(unique(table_in.(group_char))));
tmp_stats_struct = struct('sig_levels',[0.05,0.01,0.001],...
    'cond_stats',cond_stats, ...
    'group_stats',group_stats, ...
    'stats_char',struct('str',{{str}}, ...
        'offsets',[0.05,0], ...
        'font_size',12, ...
        'do_display',true));
%## PLOT
ax = axes();
%-
PLOT_STRUCT.y_label ='SPPB Total Score';
PLOT_STRUCT.ylim = [0,15];
PLOT_STRUCT.ax_position = [x_shift,y_shift,AX_W*IM_RESIZE,AX_H*IM_RESIZE];
%-
% ax = group_violin(CLIN_TABLE,'sppb_12','design_id','group_char',...
%     ax,...
%     'VIOLIN_PARAMS',VIO_PARAMS,...
%     'PLOT_STRUCT',VIO_PLOT_STRUCT,...
%     'STATS_STRUCT',tmp_stats_struct,...
%     'BRACKET_STRUCT',DEF_BRACKET_STRUCT,...
%     'SIGLINE_STRUCT',DEF_SIGLINE_STRUCT);

ax = group_violin(sppb_table,'sppb_12','condition_status','dummy_var',...
    ax,...
    'VIOLIN_STRUCT',VIOLIN_STRUCT,...
    'PLOT_STRUCT',PLOT_STRUCT,...
    'STATS_STRUCT',tmp_stats_struct,...
    'BRACKET_STRUCT',DEF_BRACKET_STRUCT,...
    'SIGLINE_STRUCT',DEF_SIGLINE_STRUCT);
%## AX SHIFT
if x_cnt < X_DIM
    x_shift = x_shift + AX_X_SHIFT*IM_RESIZE*AX_W;
else
    y_shift = y_shift - AX_Y_SHIFT*IM_RESIZE*AX_H;
    x_shift = AX_INIT_X;
    x_cnt = 0;
end
x_cnt = x_cnt + 1;
exportgraphics(fig,[tmp_savedir filesep sprintf('sppb_plot_allsubj_2g.tiff')], ...
    'Resolution',SAVE_RES)
exportgraphics(fig,[tmp_savedir filesep sprintf('sppb_plot_allsubj_2g.pdf')], ...
    'ContentType','vector')
% close(fig)